/*Problem 2: Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

#include <stdio.h>
#include <math.h>

#define PHI (1.0 + sqrt(5)) / 2.0
#define PSI 1.0 / PHI

double fib(double n);
double n_fib(double limit);
double bq_identity(double n);

int main(void)
{
    double limit = 4000000;
    double n = n_fib(limit);
    double sum = bq_identity(n / 3);
    printf("Sum of even fibs up to n: %d, %ld\n", (int)n, (long int)sum);
}

double fib(double n)
{
    double f_n = (pow(PHI, n) - pow(PSI, n)) / sqrt(5);

    return floor(f_n);
}

double n_fib(double limit)
{
    double n_fib = log((double)limit * sqrt(5.0) + 0.5) / log(PHI);

    return floor(n_fib);
}

double bq_identity(double n)
{
    return (fib(3 * floor(n) + 2)) / 2;
}